# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90ee9969830527e1f708347a9f98b9d23a763af38498ad90451da5f7a75d448f95d223f88ed00f2f63b2d97fe197fe2e31ca2200ba81b6859bfa33bdcd66b43c

test:
  secret_key_base: 3047f5637fda3e33a8892f52a2936d1e2fb070ec68bfa54ed4ebb7c4d170fd1fa3133ee3ad2127088cd0f4cd28206925cd7cd28193021801bf2cdd2f18512145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
